import React, { useState } from 'react';
import { useTraceStore } from '@/lib/store';
import { getStageHumanLabel } from '@/lib/stage-utils';
import { Flame, Zap, AlertCircle } from 'lucide-react';

export function InsightsPage() {
  const { painPoints, themes, feedbackList, isProcessing, activeStage } = useTraceStore();
  const [activeTab, setActiveTab] = useState<'top' | 'emerging'>('top');

  // Pure User Intelligence: Only display verified pain points generated by the intelligence pipeline
  const effectivePainPoints = painPoints;

  const emergingIssues = effectivePainPoints.filter(p => p.isEmerging);
  const topProblems = effectivePainPoints;

  const displayList = activeTab === 'emerging' ? emergingIssues : topProblems;
  const totalFeedbackCount = feedbackList.length;

  return (
    <div className="space-y-5 text-slate-900 dark:text-[#EDEDED]">
      {/* Top Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 border-b border-slate-200 dark:border-[#1F232B] pb-3.5">
        <div>
          <h1 className="text-xl font-bold text-slate-900 dark:text-[#EDEDED] tracking-tight">
            Insights & Problem Clusters
          </h1>
          <p className="text-xs text-slate-500 dark:text-[#8C92A4] mt-0.5 font-mono">
            Synthesized problem themes, mention frequency trends, and verbatim evidence clusters derived from verified feedback.
          </p>
        </div>
      </div>

      {/* Live Processing Indicator */}
      {isProcessing && (
        <div className="p-3.5 rounded-xl surface-card border border-emerald-500/30 flex items-center justify-between gap-3 shadow-2xs">
          <div className="flex items-center gap-2.5">
            <div className="w-2 h-2 rounded-full bg-emerald-500 animate-ping" />
            <span className="text-xs font-semibold text-emerald-700 dark:text-emerald-400">
              {getStageHumanLabel(activeStage?.stage)}
            </span>
          </div>
          <span className="text-[11px] font-mono text-slate-400 dark:text-[#8C92A4]">
            {activeStage ? `${activeStage.processedItems} of ${activeStage.totalItems} records` : 'In progress'}
          </span>
        </div>
      )}

      {/* Insufficient Evidence State (Informative Notice) */}
      {!isProcessing && totalFeedbackCount > 0 && totalFeedbackCount < 3 && (
        <div className="p-4 rounded-xl surface-card border border-amber-500/30 bg-amber-500/5 space-y-1.5 text-left">
          <div className="flex items-center gap-2 text-amber-600 dark:text-amber-400 font-bold text-xs">
            <AlertCircle className="w-4 h-4" />
            <span>PRELIMINARY CLUSTER ANALYSIS ({totalFeedbackCount} STATEMENTS)</span>
          </div>
          <p className="text-xs text-slate-600 dark:text-[#8C92A4] leading-relaxed">
            Trace has extracted preliminary friction clusters from your uploaded sample. Statistical trend corroboration improves with 3+ statements.
          </p>
        </div>
      )}

      {/* Navigation Tabs */}
      <div className="flex items-center gap-2 border-b border-slate-200 dark:border-[#1F232B] pb-3 text-xs font-semibold">
        <button
          onClick={() => setActiveTab('top')}
          className={`px-3 py-1.5 rounded-md transition-colors ${
            activeTab === 'top'
              ? 'bg-[#2E8B75]/10 text-[#2E8B75] dark:text-[#10B981] font-bold border border-[#2E8B75]/20'
              : 'text-slate-500 dark:text-[#8C92A4] hover:text-slate-900 dark:hover:text-[#EDEDED] hover:bg-slate-100 dark:hover:bg-[#181B22]'
          }`}
        >
          Top Problems ({topProblems.length})
        </button>

        <button
          onClick={() => setActiveTab('emerging')}
          className={`px-3 py-1.5 rounded-md transition-colors flex items-center gap-1.5 ${
            activeTab === 'emerging'
              ? 'bg-rose-100/80 dark:bg-rose-950/60 text-rose-800 dark:text-rose-400 border border-rose-200 dark:border-rose-900/60'
              : 'text-slate-500 dark:text-[#8C92A4] hover:text-slate-900 dark:hover:text-[#EDEDED] hover:bg-slate-100 dark:hover:bg-[#181B22]'
          }`}
        >
          <Flame className="w-3.5 h-3.5 text-rose-500" />
          <span>Emerging Issues ({emergingIssues.length})</span>
        </button>
      </div>

      {/* Cluster List */}
      <div className="space-y-3.5">
        {displayList.length === 0 ? (
          <div className="p-8 rounded-xl surface-card text-center text-xs text-slate-400 dark:text-[#525866] space-y-2">
            <Zap className="w-6 h-6 mx-auto text-slate-400 dark:text-[#525866]" />
            <p className="font-bold text-slate-700 dark:text-[#EDEDED]">No Problem Clusters Detected</p>
            <p className="text-[11px]">Import feedback datasets to synthesize automatic issue clusters and velocity spikes.</p>
          </div>
        ) : (
          displayList.map((problem) => {
            const matchingFeedback = feedbackList.filter(f =>
              problem.atomIds && problem.atomIds.length > 0
                ? f.atoms?.some(a => problem.atomIds?.includes(a.id))
                : false
            );

            const displayQuotes = matchingFeedback.slice(0, 3);

            return (
              <div key={problem.id} className="p-4 rounded-xl surface-card surface-card-hover space-y-3">
                {/* Header */}
                <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-2 border-b border-slate-100 dark:border-[#1F232B] pb-3">
                  <div>
                    <div className="flex items-center gap-2.5">
                      <h3 className="font-bold text-slate-900 dark:text-[#EDEDED] text-sm">
                        {problem.title}
                      </h3>
                      {problem.isEmerging && (
                        <span className="px-1.5 py-0.5 rounded text-[10px] font-mono font-bold bg-rose-100 dark:bg-rose-950/60 text-rose-800 dark:text-rose-400">
                          EMERGING SPIKE
                        </span>
                      )}
                      <span className="px-1.5 py-0.5 rounded text-[10px] font-mono font-bold bg-slate-100 dark:bg-[#181B22] text-slate-600 dark:text-[#8C92A4]">
                        Severity: {problem.severity.toUpperCase()}
                      </span>
                    </div>
                    <p className="text-xs text-slate-500 dark:text-[#8C92A4] mt-0.5 leading-relaxed">
                      {problem.description}
                    </p>
                  </div>

                  <div className="text-right shrink-0">
                    <span className="text-base font-bold font-mono-numbers text-slate-900 dark:text-[#EDEDED]">
                      {problem.frequency} mentions
                    </span>
                    <p className="text-[10px] font-mono text-emerald-600 dark:text-[#10B981] font-semibold">
                      +{problem.trendPercentage}% velocity
                    </p>
                  </div>
                </div>

                {/* Dynamic Segment Impact Breakdown */}
                {problem.affectedSegments && problem.affectedSegments.length > 0 && (
                  <div className="space-y-1.5">
                    <span className="text-[10px] font-semibold text-slate-400 dark:text-[#525866] uppercase font-mono tracking-wider">
                      SEGMENT DISTRIBUTION IMPACT (DETERMINISTIC)
                    </span>
                    <div className="grid grid-cols-2 sm:grid-cols-4 gap-2.5 text-xs font-mono">
                      {problem.affectedSegments.map((seg, sIdx) => (
                        <div key={sIdx} className="p-2.5 rounded-lg surface-subtle">
                          <span className="text-slate-500 dark:text-[#8C92A4] block text-[10px]">{seg.segment}</span>
                          <span className="font-bold text-slate-900 dark:text-[#EDEDED] text-sm">{seg.percentage}%</span>
                          <span className="text-[10px] text-slate-400 dark:text-[#525866] block">({seg.count} mentions)</span>
                        </div>
                      ))}
                    </div>
                  </div>
                )}

                {/* Verbatim Customer Evidence */}
                <div className="space-y-1.5 pt-1">
                  <span className="text-[10px] font-semibold text-slate-400 dark:text-[#525866] uppercase font-mono tracking-wider">
                    VERBATIM CUSTOMER EVIDENCE ({matchingFeedback.length} verified quotes)
                  </span>

                  <div className="space-y-2">
                    {displayQuotes.map(q => (
                      <div key={q.id} className="p-3 rounded-lg surface-subtle text-xs space-y-1">
                        <p className="font-medium text-slate-800 dark:text-[#C9CDD8] italic leading-relaxed">"{q.originalText}"</p>
                        <p className="text-[10px] font-mono text-slate-400 dark:text-[#525866] pt-0.5">
                          — {q.customerName || 'Anonymous Customer'} {q.customerSegmentName ? `· ${q.customerSegmentName}` : ''} · {q.sourceType.toUpperCase()}
                        </p>
                      </div>
                    ))}
                  </div>
                </div>
              </div>
            );
          })
        )}
      </div>
    </div>
  );
}
